services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - POSTGRES_HOST=database
    ports:
      - 3000:3000
    networks:
      - app_network
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app_network
networks:
  app_network:
    driver: bridge