services:
  english:
    container_name: english_container
    build: .
    volumes:
      - ./src:/app/src/
      - ./public:/app/public/
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
networks:
  app_network:
    driver: bridge