import { Toaster } from "react-hot-toast";

import "./globals.scss";
import { GoogleAuthProvider } from "./providers";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body>
				<GoogleAuthProvider>
					{children}
				</GoogleAuthProvider>
				<Toaster />
			</body>
		</html>
	);
}
